-- =============================================================================
--  Canteen POS — v1 → v2 migration for an EXISTING database.
--
--  Step 1: run THIS file (adds the new columns to your live tables).
--  Step 2: run schema.sql (it is idempotent — it creates the new tables,
--          functions, triggers and the hardened RLS policies, and will NOT
--          duplicate your data).
--  Step 3: set your real admin password hash:
--          update app_secrets set admin_hash = '<sha256-of-your-admin-password>';
-- =============================================================================

-- ---- products ---------------------------------------------------------------
alter table products add column if not exists is_deleted boolean not null default false;
alter table products add column if not exists updated_at timestamptz not null default now();

-- Clamp any bad legacy data before adding the constraints.
update products set quantity = 0 where quantity < 0;
update products set price = 0 where price < 0;

do $$ begin
  alter table products add constraint chk_products_qty_nonneg check (quantity >= 0);
exception when duplicate_object then null; end $$;

do $$ begin
  alter table products add constraint chk_products_price_nonneg check (price >= 0);
exception when duplicate_object then null; end $$;

-- ---- sales ------------------------------------------------------------------
alter table sales add column if not exists order_no bigint generated by default as identity;
alter table sales add column if not exists status text not null default 'completed';
alter table sales add column if not exists refunded_at timestamptz;
alter table sales add column if not exists refunded_by text;
alter table sales add column if not exists refund_reason text;

do $$ begin
  alter table sales add constraint sales_order_no_key unique (order_no);
exception when duplicate_object then null; end $$;

do $$ begin
  alter table sales add constraint chk_sales_status check (status in ('completed','refunded'));
exception when duplicate_object then null; end $$;

-- Give pre-existing sales sequential order numbers by date (identity already
-- assigned defaults; this keeps chronological order readable).
-- (No action needed — identity default already backfilled on ADD COLUMN.)

-- Now run schema.sql for the rest (logs, daily_reports, app_secrets, RPCs, RLS).
