-- =============================================================================
--  Canteen POS — Supabase / PostgreSQL schema  (v2 — production hardened)
--  Run this in the Supabase dashboard → SQL Editor → New query → Run.
--
--  Fresh install: run this whole file.
--  Existing database (v1): run migration.sql instead.
--
--  v2 adds: audit logs, daily closing reports, soft delete, refunds,
--  human-friendly order numbers, non-negative stock enforcement, and atomic
--  SECURITY DEFINER functions so every financial action is validated AND
--  logged inside the database — not just in the browser.
-- =============================================================================

create extension if not exists pgcrypto;   -- for gen_random_uuid() + digest()

-- ----------------------------------------------------------------------------
--  Tables
-- ----------------------------------------------------------------------------
create table if not exists products (
  id          uuid primary key default gen_random_uuid(),
  name        text not null check (length(trim(name)) between 1 and 120),
  price       numeric(10,2) not null default 0 check (price >= 0),
  category    text,
  image_url   text,
  quantity    integer not null default 0 check (quantity >= 0),  -- stock can never go negative
  code        text,
  is_deleted  boolean not null default false,                    -- soft delete only
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists sales (
  id            uuid primary key default gen_random_uuid(),
  order_no      bigint generated by default as identity unique,  -- human-friendly invoice number
  total_price   numeric(10,2) not null default 0 check (total_price >= 0),
  seller_name   text,
  status        text not null default 'completed' check (status in ('completed','refunded')),
  refunded_at   timestamptz,
  refunded_by   text,
  refund_reason text,
  created_at    timestamptz not null default now()
);

create table if not exists sale_items (
  id             uuid primary key default gen_random_uuid(),
  sale_id        uuid not null references sales(id) on delete cascade,
  product_id     uuid references products(id) on delete set null,
  quantity       integer not null default 1 check (quantity > 0),
  price_at_sale  numeric(10,2) not null default 0 check (price_at_sale >= 0)
);

-- Append-only audit trail. RLS below allows INSERT + SELECT only — rows can
-- never be updated or deleted through the API.
create table if not exists logs (
  id          bigint generated by default as identity primary key,
  user_name   text not null default 'unknown',
  action      text not null,          -- product_add / product_update / product_delete /
                                      -- price_change / sale / refund / daily_close / login
  details     jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

-- One immutable closing report per calendar day (Africa/Cairo).
create table if not exists daily_reports (
  id            bigint generated by default as identity primary key,
  report_date   date not null unique,
  total_sales   numeric(12,2) not null default 0,
  orders_count  integer not null default 0,
  expected_cash numeric(12,2) not null default 0,
  actual_cash   numeric(12,2) not null default 0,
  difference    numeric(12,2) not null default 0,   -- actual − expected
  closed_by     text,
  notes         text,
  created_at    timestamptz not null default now()
);

create index if not exists idx_sale_items_sale     on sale_items(sale_id);
create index if not exists idx_sale_items_product  on sale_items(product_id);
create index if not exists idx_sales_created       on sales(created_at desc);
create index if not exists idx_products_category   on products(category);
create index if not exists idx_logs_created        on logs(created_at desc);

-- Keep products.updated_at fresh automatically.
create or replace function touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists trg_products_touch on products;
create trigger trg_products_touch before update on products
  for each row execute function touch_updated_at();

-- ----------------------------------------------------------------------------
--  Row Level Security
--
--  No Supabase Auth — every request arrives as `anon`. The policies below are
--  deliberately granular:
--    • NOTHING can be deleted through the API (no DELETE policy on any table).
--    • logs + daily_reports are append-only (INSERT + SELECT, never UPDATE).
--    • sale_items can never be rewritten after a sale (INSERT + SELECT only).
--  Financial mutations (checkout, refunds, price changes, daily close) go
--  through the SECURITY DEFINER functions further down, which validate and
--  audit-log server-side.
-- ----------------------------------------------------------------------------
alter table products      enable row level security;
alter table sales         enable row level security;
alter table sale_items    enable row level security;
alter table logs          enable row level security;
alter table daily_reports enable row level security;

drop policy if exists p_products_all    on products;
drop policy if exists p_sales_all       on sales;
drop policy if exists p_sale_items_all  on sale_items;
drop policy if exists p_products_select on products;
drop policy if exists p_products_insert on products;
drop policy if exists p_products_update on products;
drop policy if exists p_sales_select    on sales;
drop policy if exists p_sales_insert    on sales;
drop policy if exists p_sale_items_select on sale_items;
drop policy if exists p_sale_items_insert on sale_items;
drop policy if exists p_logs_select     on logs;
drop policy if exists p_logs_insert     on logs;
drop policy if exists p_reports_select  on daily_reports;
drop policy if exists p_reports_insert  on daily_reports;

create policy p_products_select on products for select to anon using (true);
create policy p_products_insert on products for insert to anon with check (true);
create policy p_products_update on products for update to anon using (true) with check (true);

create policy p_sales_select on sales for select to anon using (true);
create policy p_sales_insert on sales for insert to anon with check (true);
-- no UPDATE policy on sales: refunds go through refund_sale() below.

create policy p_sale_items_select on sale_items for select to anon using (true);
create policy p_sale_items_insert on sale_items for insert to anon with check (true);

create policy p_logs_select on logs for select to anon using (true);
create policy p_logs_insert on logs for insert to anon with check (true);

create policy p_reports_select on daily_reports for select to anon using (true);
create policy p_reports_insert on daily_reports for insert to anon with check (true);

-- ----------------------------------------------------------------------------
--  Admin secret — used by update_product_price() and refund_sale() so the
--  admin password is verified inside PostgreSQL, not only in the browser.
--  Default hash is SHA-256 of "admin" — REPLACE IT (run in browser console:
--  await hashText('your-password')).
-- ----------------------------------------------------------------------------
create table if not exists app_secrets (
  id         int primary key default 1,
  admin_hash text not null,
  check (id = 1)
);
alter table app_secrets enable row level security;   -- no anon policy = unreadable

insert into app_secrets (id, admin_hash)
  values (1, '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918')
  on conflict (id) do nothing;

-- search_path includes `extensions` because Supabase installs pgcrypto
-- (digest) there rather than in `public`.
create or replace function verify_admin(p_password text) returns boolean
language sql security definer set search_path = public, extensions as $$
  select coalesce(
    (select admin_hash = encode(digest(p_password, 'sha256'), 'hex') from app_secrets where id = 1),
    false);
$$;
revoke all on function verify_admin(text) from public;

-- ----------------------------------------------------------------------------
--  process_sale — atomic checkout.
--  Locks each product row, rejects insufficient stock, uses DATABASE prices
--  (never client-supplied prices), writes the sale + items, decrements stock,
--  and audit-logs — all in one transaction.
--  p_items: [{"id": "<uuid>", "quantity": 2}, ...]
-- ----------------------------------------------------------------------------
create or replace function process_sale(p_items jsonb, p_seller text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale     sales;
  v_item     jsonb;
  v_product  products;
  v_qty      integer;
  v_total    numeric(12,2) := 0;
  v_log      jsonb := '[]'::jsonb;
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'EMPTY_CART';
  end if;

  -- Pass 1: lock + validate every line, total from DB prices.
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := (v_item->>'quantity')::integer;
    if v_qty is null or v_qty <= 0 or v_qty > 1000 then
      raise exception 'BAD_QUANTITY';
    end if;
    select * into v_product from products
      where id = (v_item->>'id')::uuid and is_deleted = false
      for update;
    if not found then
      raise exception 'PRODUCT_NOT_FOUND';
    end if;
    if v_product.quantity < v_qty then
      raise exception 'INSUFFICIENT_STOCK:%:%', v_product.name, v_product.quantity;
    end if;
    v_total := v_total + (v_product.price * v_qty);
  end loop;

  insert into sales (total_price, seller_name)
    values (v_total, coalesce(p_seller, 'seller'))
    returning * into v_sale;

  -- Pass 2: write items + decrement stock (rows already locked).
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := (v_item->>'quantity')::integer;
    select * into v_product from products where id = (v_item->>'id')::uuid;
    insert into sale_items (sale_id, product_id, quantity, price_at_sale)
      values (v_sale.id, v_product.id, v_qty, v_product.price);
    update products set quantity = quantity - v_qty where id = v_product.id;
    v_log := v_log || jsonb_build_object('product', v_product.name, 'qty', v_qty, 'price', v_product.price);
  end loop;

  insert into logs (user_name, action, details)
    values (coalesce(p_seller, 'seller'), 'sale',
            jsonb_build_object('sale_id', v_sale.id, 'order_no', v_sale.order_no,
                               'total', v_total, 'items', v_log));

  return to_jsonb(v_sale);
end $$;

revoke all on function process_sale(jsonb, text) from public;
grant execute on function process_sale(jsonb, text) to anon;

-- ----------------------------------------------------------------------------
--  refund_sale — admin-verified refund. Restores stock, marks the sale
--  refunded (never deletes it), audit-logs. Refusing double refunds.
-- ----------------------------------------------------------------------------
create or replace function refund_sale(p_sale_id uuid, p_password text, p_user text, p_reason text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale sales;
  v_item record;
begin
  if not verify_admin(p_password) then
    raise exception 'INVALID_ADMIN_PASSWORD';
  end if;

  select * into v_sale from sales where id = p_sale_id for update;
  if not found then
    raise exception 'SALE_NOT_FOUND';
  end if;
  if v_sale.status = 'refunded' then
    raise exception 'ALREADY_REFUNDED';
  end if;

  -- Restore stock for every line that still points at a product.
  for v_item in select product_id, quantity from sale_items where sale_id = p_sale_id and product_id is not null loop
    update products set quantity = quantity + v_item.quantity where id = v_item.product_id;
  end loop;

  update sales
     set status = 'refunded', refunded_at = now(),
         refunded_by = coalesce(p_user, 'admin'), refund_reason = p_reason
   where id = p_sale_id
   returning * into v_sale;

  insert into logs (user_name, action, details)
    values (coalesce(p_user, 'admin'), 'refund',
            jsonb_build_object('sale_id', v_sale.id, 'order_no', v_sale.order_no,
                               'total', v_sale.total_price, 'reason', p_reason));

  return to_jsonb(v_sale);
end $$;

revoke all on function refund_sale(uuid, text, text, text) from public;
grant execute on function refund_sale(uuid, text, text, text) to anon;

-- ----------------------------------------------------------------------------
--  update_product_price — admin-verified price change, logs old → new.
-- ----------------------------------------------------------------------------
create or replace function update_product_price(p_id uuid, p_price numeric, p_password text, p_user text default 'admin')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old numeric(10,2);
  v_row products;
begin
  if not verify_admin(p_password) then
    raise exception 'INVALID_ADMIN_PASSWORD';
  end if;
  if p_price is null or p_price < 0 or p_price > 100000 then
    raise exception 'BAD_PRICE';
  end if;

  select price into v_old from products where id = p_id for update;
  if not found then
    raise exception 'PRODUCT_NOT_FOUND';
  end if;

  update products set price = p_price where id = p_id returning * into v_row;

  insert into logs (user_name, action, details)
    values (coalesce(p_user, 'admin'), 'price_change',
            jsonb_build_object('product_id', p_id, 'name', v_row.name,
                               'old_price', v_old, 'new_price', p_price));

  return to_jsonb(v_row);
end $$;

revoke all on function update_product_price(uuid, numeric, text, text) from public;
grant execute on function update_product_price(uuid, numeric, text, text) to anon;

-- ----------------------------------------------------------------------------
--  close_day — daily closing. Totals are computed IN the database for the
--  Cairo calendar day, the report row is immutable (unique per day, no UPDATE
--  policy), and the closing is audit-logged.
-- ----------------------------------------------------------------------------
create or replace function close_day(p_actual_cash numeric, p_password text, p_user text default 'admin', p_notes text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_date   date := (now() at time zone 'Africa/Cairo')::date;
  v_total  numeric(12,2);
  v_count  integer;
  v_report daily_reports;
begin
  if not verify_admin(p_password) then
    raise exception 'INVALID_ADMIN_PASSWORD';
  end if;
  if p_actual_cash is null or p_actual_cash < 0 then
    raise exception 'BAD_CASH_AMOUNT';
  end if;
  if exists (select 1 from daily_reports where report_date = v_date) then
    raise exception 'DAY_ALREADY_CLOSED';
  end if;

  select coalesce(sum(total_price), 0), count(*)
    into v_total, v_count
    from sales
   where status = 'completed'
     and (created_at at time zone 'Africa/Cairo')::date = v_date;

  insert into daily_reports (report_date, total_sales, orders_count, expected_cash,
                             actual_cash, difference, closed_by, notes)
    values (v_date, v_total, v_count, v_total, p_actual_cash,
            p_actual_cash - v_total, coalesce(p_user, 'admin'), p_notes)
    returning * into v_report;

  insert into logs (user_name, action, details)
    values (coalesce(p_user, 'admin'), 'daily_close',
            jsonb_build_object('date', v_date, 'total_sales', v_total, 'orders', v_count,
                               'actual_cash', p_actual_cash, 'difference', p_actual_cash - v_total));

  return to_jsonb(v_report);
end $$;

revoke all on function close_day(numeric, text, text, text) from public;
grant execute on function close_day(numeric, text, text, text) to anon;

-- ----------------------------------------------------------------------------
--  Sample products — only inserted into an EMPTY products table, so this file
--  is safe to re-run against a live database.
-- ----------------------------------------------------------------------------
insert into products (name, price, category, quantity, code)
select * from (values
  ('شاي كركديه',        10.00, 'مشروبات',  40, 'DR01'),
  ('قهوة تركي',         15.00, 'مشروبات',  30, 'DR02'),
  ('مياه معدنية',        5.00, 'مشروبات', 120, 'DR03'),
  ('ساندويتش جبنة',     20.00, 'مأكولات',  25, 'FD01'),
  ('فطير',              25.00, 'مأكولات',  18, 'FD02'),
  ('قطعة بسبوسة',       12.00, 'حلويات',   35, 'SW01'),
  ('لوح شوكولاتة',       8.00, 'حلويات',   60, 'SW02'),
  ('شيبسي',              7.00, 'سناكس',    80, 'SN01')
) as v(name, price, category, quantity, code)
where not exists (select 1 from products);
